BASE_YAML: "COCO-Detection/faster_rcnn_R_101_C4_3x.yaml"

DATASETS:
  TRAIN: ("daytime_clear_train",)
  TEST: ("daytime_clear_test",)

DATALOADER:
  NUM_WORKERS: 16

INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TEST: 640
  CLIP_RANDOM_CROPS: True
  RANDOM_CROP_SIZE: 320
  RANDOM_CROP_NUM: 4

SOLVER:
  BASE_LR: 0.0005
  MAX_ITER: 400000
  STEPS: [80000,]
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 5000

MODEL:
  BACKBONE:
    NAME: ClipRN101
  WEIGHTS: ""
  CLIP_IMAGE_ENCODER_NAME: "RN101"
  META_ARCHITECTURE: "ClipRCNNMRDCOT"
  STYLE_CHANNELS: 256
  NUM_CLASSES: 7
  COT_FILES: ["cot30_1.txt", "cot30_2.txt", "cot30_3.txt"]
  COT_STYLE_SAMPLE_NUM: 2
  SOURCE_STYLE_TEXT: "Sunny, Day, Driving"
  STYLE_COMBINE_PROB: 0.3
  DISENTANGLE_TAU: 1.0
  LOSS_WEIGHT_SC: 1.0
  LOSS_WEIGHT_GC: 1.0
  LOSS_WEIGHT_DIS: 1.0
  MR_VISUAL_NOISE_STD: 0.08
  MR_BLUR_KERNEL: 3
  MR_BLUR_PROB: 0.5
  MR_LOSS_WEIGHT_ALIGN: 0.5
  MR_LOSS_WEIGHT_DIFF: 0.25
  MR_LOSS_WEIGHT_REG: 0.5
  MR_LOSS_WEIGHT_LOCAL: 0.5
  MR_TEMPERATURE: 0.1
  PROPOSAL_GENERATOR:
    NAME: "SBRPN"
  ROI_HEADS:
    NAME: "ClipRes5ROIHeadsAttn"
    NUM_CLASSES: 7

TEST:
  EVAL_PERIOD: 5000  
  EVAL_SAVE_PERIOD: 5000

OUTPUT_DIR: "all_outs/diverse_weather_mrdcot"

OFFSET_OPT_INTERVAL: [100000]
OFFSET_OPT_ITERS: 1000
OFFSET_OPT_LR: 1.0
AUG_PROB: 0.5

VIS_PERIOD: 0
